# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
  app:
    image: openaigurad
    build: ./OpenAI-Guardian
    depends_on:
      - guardian
    volumes:
      - ./config.yml:/code/config.yml
  guardian:
    image: guardian
    build: ./Granite-Guardian
    # this model need GPU to run
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./Granite-Guardian/model:/code/model
  mitmproxy:
    image: my_mitmproxy
    build: ./mitmproxy
    ports:
      - "8080:8080"
    depends_on:
      - guardian
      - app
    command: mitmdump -s /code/intercept_openai.py --mode reverse:https://api.openai.com
    volumes:
      - ./mitmproxy/code/intercept_openai.py:/code/intercept_openai.py
      - ~/.mitmproxy:/home/mitmproxy/.mitmproxy