# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
  app:
    image: openaigurad
    build: ./OpenAI-Guardian
    volumes:
      - ./config.yml:/code/config.yml

  mitmproxy:
    image: mitmproxy/mitmproxy
    ports:
      - "8080:8080"
    depends_on:
      - app
    command: mitmdump -s /code/intercept_openai.py --mode reverse:https://api.openai.com
    volumes:
      - ./mitmproxy/intercept_openai.py:/code/intercept_openai.py
      - ~/.mitmproxy:/home/mitmproxy/.mitmproxy