# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs 
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - guardian
      - mitmproxy

  guardian:
    # x86 cpu image
    build:
      context: ./vllm
      dockerfile: ./vllm/Dockerfile.cpu
      shm_size: '4g'
    image: vllm-guardian
    environment:
      - VLLM_CPU_KVCACHE_SPACE=10 # you can increase this if you have more memory
    command: --model /model
    ports:
      - "8000:8000"
    volumes:
      - ./model:/model
  mitmproxy:
    image: my_mitmproxy
    build: ./mitmproxy
    ports:
      - "8080:8080"
    command: mitmdump -s /code/intercept_openai.py --mode reverse:https://api.openai.com
    volumes:
      - ./mitmproxy/code/intercept_openai.py:/code/intercept_openai.py
      - ~/.mitmproxy:/home/mitmproxy/.mitmproxy